#!/bin/bash
#
# 2022.02.23 - Matteo Chesi
#
function help() {
  SCRIPTNAME=`basename $0`

cat << EOF

    This script makes a RockyLinux system appear as a CentOS one.

    Usage: ${SCRIPTNAME} <OPTIONS>

    Options:
 
    --revert|-r : revert changes

    --help|-h   : print help message

EOF
}

function rocky2centos() {
  . /etc/os-release
  if [ "$ID" != "rocky" ]
  then
    echo "Linux distro isn't Rocky... skipping"
    exit 0
  fi

  echo 'CentOS Linux release 8.4.2105' > /etc/centos-release
  rm -f /etc/redhat-release
  ln -s centos-release /etc/redhat-release  
  rm -f /etc/system-release
  ln -s centos-release /etc/system-release  
cat << EOF >/usr/lib/os-release.centos
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
EOF
  cp -a /usr/lib/os-release /usr/lib/os-release.rocky
  cp -a /usr/lib/os-release.centos /usr/lib/os-release
}

function centos2rocky() {
  . /etc/os-release
  if [ "$ID" != "centos" ]
  then
    echo "Linux distro isn't CentOS... skipping"
    exit 0
  fi

  rm -f /etc/redhat-release
  ln -s rocky-release /etc/redhat-release  
  rm -f /etc/system-release
  ln -s rocky-release /etc/system-release  
  cp -a /usr/lib/os-release.rocky /usr/lib/os-release
}

function parse_args() {
  case $1 in
    '')
      rocky2centos
      ;;
    --revert|-r)
      centos2rocky
      ;;
    --help|-h)
      help
      ;;
    *)
      echo "Error. Unrecognized command: $1"
      help
      exit 1
      ;;		
  esac	
}

parse_args $@
exit 0
